application: adieu-backend
version: 2
runtime: python
api_version: 1

handlers:
##
# Adieu application
##
# Services.
- url: /item/.*
  script: item.py

- url: /comment/.*
  script: comment.py

- url: /vote/.*
  script: vote.py


##
# Midautumn application
##
# Services
- url: /api/.*
  script: midautumn/api.py

# Static URIs.
- url: /robots.txt
  static_files: midautumn/robots.txt
  upload: midautumn/robots.txt

- url: /favicon.ico
  static_files: midautumn/img/favicon.ico
  upload: midautumn/img/favicon.ico

- url: /css
  static_dir: midautumn/css

- url: /img
  static_dir: midautumn/img

- url: /js
  static_dir: midautumn/js

# Entries
- url: .*
  script: midautumn/main.py
